### ISSUE TITLE
Please remove M2_HOME instructions

### ISSUE THREAD

**Issue by dantran** [sonatype/maven-reference-en#15]
see https://jira.codehaus.org/browse/MNGSITE-223

**Comment by mosabua** [comment]
@dantran do you want me to remove this now or when the site is updated (e.a. the issue is closed).

**Comment by dantran** [comment]
@manfred I closed the issue. So you can fix it now

**Comment by Manfred** [comment]
Wrong Manfred :id:

**Comment by mosabua** [comment]
This is now updated and published. See http://books.sonatype.com/mvnref-book/reference/installation-sect-maven-install.html
