### ISSUE TITLE
In the chapter http://books.sonatype.com/mvnref-book/reference/running-sect-options.html

### ISSUE THREAD

**Issue by khmarbaise** [sonatype/maven-reference-en#16]
There is a reference on a Maven 2.X option -r / --reactor see 6.1.2. Getting Help.
The question is if this appropriate to document options which are no longer valid for Maven 3?

**Comment by mosabua** [comment]
The book was based on Maven 2 and 3 and has never been fully updated. We take pull requests though. In this case I can just remove the reference.

**Comment by khmarbaise** [comment]
Ah ok.. No problem i can create a pull request for it if this is prefered way.
