### ISSUE TITLE
Warning during build: book-mvnref-docinfo.html: file does not exist

### ISSUE THREAD

**Issue by archiecobbs** [sonatype/maven-reference-en#25]
Running `./build.sh` on openSUSE 13.2, the first line output is this warning:

    asciidoc: WARNING: book-mvnref.asciidoc: line 5: {include:/home/foo/maven-reference-en/book-mvnref-docinfo.html}: file does not exist

The build seems to proceed OK.

**Comment by mosabua** [comment]
This is a known warning and causes no problems
